### PR TITLE
Project class v1.0.0

### PR DESCRIPTION
**Pull request by zartre**
Please look into CHANGELOG.md for details.

### CODE REVIEW

**Review by sagelga — APPROVED** [review]
~These set of files looks clean and 100% safe to Merge~
I clicked the wrong button. Please ignore this approval.

**Review by sagelga — CHANGES_REQUESTED** [review]
Some files are not kept up with master.
and this PR might blocking this PR.
- https://github.com/DobaKung/IT-KMITL-Latex/pull/19

and I have fixed the conflicts with this PR
- https://github.com/DobaKung/IT-KMITL-Latex/pull/21 
- https://github.com/dsmlr/IT-KMITL-Latex/pull/7

**Comment by zartre** [comment]
@sagelga Can you write a changelog?

**Comment by zartre** [comment]
@chin8628 ถ้าสะดวกฝากดู PR นี้ด้วยนะครับ

**Comment by sagelga** [comment]
@DobaKung ready to merge?

**Review by sagelga — APPROVED** [review]
Everything is ready for merge.
No code check error is fine by me.

**Comment by chin8628** [comment]
เราฝากให้ @phongsathorn1 merge ละ เรากดออกจากคนดูแลแล้ว 5555

**Pull request merged**
